db:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
    - ./datadir:/data/db

api:
  build: ./api
  ports:
    - "9292:9292"
  volumes:
    - ./api:/code
  command: "./start_dev_server.sh"
  links:
    - db
  environment:
    - RACK_ENV=development
    - MONGO_SERVER=db
    - MONGO_DATABASE=password_storage
    - MONGO_PORT=27017
    - MONGO_USER=""
    - MONGO_PASSWORD=""

web:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./client:/usr/share/nginx/html
  command: nginx -g "daemon off;"

