development:
  sessions:
    default:
      database: password_storage
      hosts:
        - db:27017

test:
  sessions:
    default:
      database: password_storage_test
      hosts:
        - db:27017