production:
  clients:
    default:
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - <%= ENV['MONGO_SERVER'] %>:<%= ENV['MONGO_PORT'] %>
      options:
        user: '<%= ENV['MONGO_USER'] %>'
        password: '<%= ENV['MONGO_PASSWORD'] %>'

development:
  clients:
    default:
      database: password_storage
      hosts:
        - db:27017

test:
  clients:
    default:
      database: password_storage_test
      hosts:
        - db:27017