production:
  sessions:
    default:
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - <%= ENV['MONGO_SERVER'] %>:<%= ENV['MONGO_PORT'] %>
      username: '<%= ENV['MONGO_USER'] %>'
      password: '<%= ENV['MONGO_PASSWORD'] %>'

development:
  sessions:
    default:
      database: <%= ENV['MONGO_DATABASE'] %>
      hosts:
        - <%= ENV['MONGO_SERVER'] %>:<%= ENV['MONGO_PORT'] %>

test:
  sessions:
    default:
      database: password_storage_test
      hosts:
        - db:27017