require 'rake'
require 'rspec/core/rake_task'

require_relative 'bootstrap'

task :environment do
end

spec = Gem::Specification.find_by_name 'mongoid'
load "#{spec.gem_dir}/lib/mongoid/tasks/database.rake"

namespace :db do
  desc "Seed"
  task :seed do
    require_relative 'db/seeds'
  end
end

RSpec::Core::RakeTask.new("test", [:only_module]) do |t, args|
  t.verbose = true
  t.fail_on_error = true
  t.rspec_opts = ["--drb", "-Ilib","--format documentation","--color", "--fail-fast"]
  t.pattern = []

  PasswordStorage::modules.each do |mod|
    module_name = mod.name.split('::').last.downcase
    if args.only_module && args.only_module != module_name
      # pass
    else
      t.pattern << "#{mod.path}/test/*_spec.rb"
    end
  end
end