require 'rake'

require_relative 'bootstrap'

task :environment do
end

spec = Gem::Specification.find_by_name 'mongoid'
load "#{spec.gem_dir}/lib/mongoid/tasks/database.rake"

namespace :db do
  desc "Seed"
  task :seed do
    require_relative 'db/seeds'
  end
end